name: Code Style
on:
  push:
    branches: 'main'
jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install pylint and mypy
        run: pip install pylint mypy
      - name: Run pylint
        run: python3 -m pylint .
      - name: Run mypy
        run: python3 -m mypy .
  deploy-to-gcloud:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on:  ubuntu-latest
    steps:
      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v2
        with:
          service_account: "418801320409-compute@developer.gserviceaccount.com"
          project_id: "devops-team-15-124368"
          workload_identity_provider: "projects/418801320409/locations/global/workloadIdentityPools/github/providers/my-repo"
