name: Code Style and Deploy
on:
  push:
    branches: 'main'
jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install pylint and mypy
        run: pip install pylint mypy
      - name: Run pylint on dog.py
        run: python3 -m pylint server/py/dog.py
      - name: Run mypy on dog.py
        run: python3 -m mypy --ignore-missing-imports server/py/dog.py

  deploy-to-gcloud:
    needs: code-style
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v2
        with:
          service_account: "418801320409-compute@developer.gserviceaccount.com"
          project_id: "devops-team-15-124368"
          workload_identity_provider: "projects/418801320409/locations/global/workloadIdentityPools/github/providers/my-repo"
      - name: Set up Google Cloud SDK
        run: |
          gcloud config set project ${{ secrets.PROJECT_ID }}
          gcloud config set compute/zone ${{ secrets.ZONE }}
      - name: Build and Deploy to Cloud Run
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.PROJECT_ID }}/myapp
          gcloud run deploy myapp --image gcr.io/${{ secrets.PROJECT_ID }}/myapp --platform managed --allow-unauthenticated
