name: Code Style and Deploy
on:
  push:
    branches: 'main'
jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt  # This installs all dependencies, including pylint and mypy

      - name: Run pylint on dog.py
        run: python3 -m pylint server/py/dog.py
      - name: Run mypy on dog.py
        run: python3 -m mypy --ignore-missing-imports server/py/dog.py

  deploy-to-gcloud:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v2
        with:
          service_account: "418801320409-compute@developer.gserviceaccount.com"
          project_id: "devops-team-15-124368"
          workload_identity_provider: "projects/418801320409/locations/global/workloadIdentityPools/github/providers/my-repo"
      - name: Set up Google Cloud SDK
        run: |
          gcloud config set project ${{ secrets.PROJECT_ID }}
          gcloud config set compute/zone ${{ secrets.ZONE }}
          gcloud config set run/region europe-west6
      - name: List files recursively
        run: find . -type f
      - name: Print GitHub workspace path
        run: echo "Workspace path is $GITHUB_WORKSPACE"
      - name: List contents of GitHub workspace
        run: ls -la $GITHUB_WORKSPACE
      - name: Check detailed contents recursively in workspace
        run: find $GITHUB_WORKSPACE -type f
      - name: Build and Deploy to Cloud Run
        run: |
          gcloud run deploy game-server-service-from-command-line --port 8080 --source . --allow-unauthenticated
      
